### PR TITLE
Do not pass mfg prefix

### PR DESCRIPTION
**Pull request by bukepo**

### CODE REVIEW

**Comment by bukepo** [comment]
@abtink this PR eliminating transmitting `mfg` prefix of diagnostic commands. This unifies the behavior of RCP and NCP about the `NEST_STREAM_MFG` property.

**Comment by bukepo** [comment]
@abtink any comments?

**Comment by bukepo** [comment]
@abtink ping.

**Comment by abtink** [comment]
This changes the behavior in `wpantund` so that we don't send `mfg` as part of the string.
How is it handled in OT diags module then?
Wouldnt it expect to see "mfg" as first part? How would be work with platform diags commands?

**Comment by abtink** [comment]
I did check the OT code. I see with have a sort of work-around.
```
818998e609 src/ncp/ncp_base.cpp     (Buke Po            2017-08-04 01:19:07 +0800 1292) #if OPENTHREAD_MTD || OPENTHREAD_FTD
cdc3751e59 src/ncp/ncp_base.cpp     (Yakun Xu           2019-08-15 13:21:58 +0800 1293)     // TODO do not pass mfg prefix
cdc3751e59 src/ncp/ncp_base.cpp     (Yakun Xu           2019-08-15 13:21:58 +0800 1294)     // skip mfg prefix from wpantund
cdc3751e59 src/ncp/ncp_base.cpp     (Yakun Xu           2019-08-15 13:21:58 +0800 1295)     if (memcmp(string, "mfg ", 4) == 0)
cdc3751e59 src/ncp/ncp_base.cpp     (Yakun Xu           2019-08-15 13:21:58 +0800 1296)     {
cdc3751e59 src/ncp/ncp_base.cpp     (Yakun Xu           2019-08-15 13:21:58 +0800 1297)         string += 4;
cdc3751e59 src/ncp/ncp_base.cpp     (Yakun Xu           2019-08-15 13:21:58 +0800 1298)     }
cdc3751e59 src/ncp/ncp_base.cpp     (Yakun Xu           2019-08-15 13:21:58 +0800 1299) #endif
````

**Comment by abtink** [comment]
`otDiagProcessCmdLine()` also seem to drop the first argv entry! I asumme that would be `"diag"` before actual command, right?

**Comment by bukepo** [comment]
Yes, the difference caused our internal diagnostic feature broken. That's why I submitted that work-around as a hot fix.

**Comment by bukepo** [comment]
After we agreed on this change and get this merged. I will remove that workaround in OpenThread. Then I will start another sync includes both OpenThread and wpantund.

**Comment by abtink** [comment]
Got it. Sounds good! Thanks. Merged it.

**Pull request merged**
