### PR TITLE
Correct path of dbus plist

### PR DESCRIPTION
**Pull request by bukepo**
I did according to the installation guide, finding that the d-bus path is incorrect.

### CODE REVIEW

**Comment by beriberikix** [comment]
@bukepo did you see #136?

**Comment by bukepo** [comment]
@beriberikix thanks. I will close this PR. And could you please fix them soon. I believe more people will also be confused.

**Comment by beriberikix** [comment]
I hadn't submitted a PR because I was running into other issues in the simulator tutorial. I'll try to get it all working today.

**Comment by beriberikix** [comment]
@bukepo I had to use `"$(brew --cellar)"/dbus/*/org.freedesktop.dbus-session.plist` instead. Did `"$(brew --repository)"/Cellar/dbus/*/org.freedesktop.dbus-session.plist` work for you?

**Comment by bukepo** [comment]
Yes, it works for me.

**Pull request closed without merging**
