### PR TITLE
add support for Thread 1.2 Backbone Router properties

### PR DESCRIPTION
**Pull request by piotrkoziar**
Related PR into OpenThread: https://github.com/openthread/openthread/pull/6232

### CODE REVIEW

**Comment by konradderda** [comment]
@googlebot I consent

**Review by abtink — APPROVED** [review]
LGTM. 👍

**Comment by abtink** [comment]
@piotrkoziar can you please help rebase it and fix the conflicts? Thanks. It LGTM.

**Comment by piotrkoziar** [comment]
Rebased

**Pull request merged**
